* Holy grail demo

** What is it?

This demonstrates the “holy grail” workflow for web development the way I envision it: a restartable back-end in the REPL + a hot-reloadable front-end in the browser. 

** Demo 

Clone this repo, cd into it; and type on the command line:

#+BEGIN_SRC shell
$ boot dev
#+END_SRC

Connect to the headless REPL (*M-x cider-connect* in Emacs works great). Type:
#+BEGIN_SRC clojure
(go)
#+END_SRC

In the browser, go to http://localhost:3000

You will see a simple web app that doesn’t do much, but the point is the workflow. In other words, how you can take it from here to develop both APIs and client-side functionality in the most comfortable way. Let’s demonstrate this. 

Open the file *src/clj/real_time/handler.clj*, and let’s add a route: 
#+BEGIN_SRC clojure
(defroutes app-routes
  (GET "/" [] (-> (resp/resource-response "index.html")
                     (resp/content-type "text/html")))
  (GET "/foo" [] (str "<h1>Hello, world</h1>")) ;; let’s add this
  (route/not-found "Not Found"))

#+END_SRC

Now save the file, go to your REPL, and type:

#+BEGIN_SRC clojure
(reset)
#+END_SRC

In the browser, type http://localhost:3000/foo. You’ve just worked on the backend, made a change, and restarted it from the REPL. How cool is that?

Now let’s do a change client-side. Open *src/clj/real_time/handler.clj* and on line 26 change the string for Value from “submit” to “send”. Save the file. The change is reflected automatically in the browser. How cool is that?

You’re all set to dive into the zone for endless hours of sheer creative genius! 
